In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../raw_results/results_S1_dahlou_ncp_cov_run1.csv")

In [3]:
df.head()

,Run_ID,Parameter,Estimate,2.5%,97.5%,R_hat,ESS,MCSE,ESS_sec,Time_s,Divergences,Max_Treedepths,E_BFMI
0,1,"xi[1,1353]",6.838460,1.474140,12.65590,1.001440,4175.96,0.044309,0.008519,490180.427193,0,0,0.67905
1,1,"b_raw[478,6]",1.736510,0.596657,3.00594,0.999957,6238.13,0.007729,0.012726,490180.427193,0,0,0.67905
2,1,"xi_raw[3,128]",0.198045,-1.651160,2.01920,1.001160,12349.30,0.008351,0.025193,490180.427193,0,0,0.67905
3,1,"xi[4,3417]",3.639360,-0.395025,8.35707,1.000200,10044.50,0.023084,0.020491,490180.427193,0,0,0.67905
4,1,"b[242,1]",2.711760,-2.184620,7.93422,1.000150,7483.18,0.029793,0.015266,490180.427193,0,0,0.67905

In [4]:
filtered_df = df[df["Parameter"].str.contains("alpha_dyn", na=False)]
filtered_df

,Run_ID,Parameter,Estimate,2.5%,97.5%,R_hat,ESS,MCSE,ESS_sec,Time_s,Divergences,Max_Treedepths,E_BFMI
7502,1,"alpha_dyn[3,3]",0.404990,-0.094478,0.894990,1.00034,3499.48,0.004265,0.007139,490180.427193,0,0,0.67905
11238,1,"alpha_dyn[1,3]",0.608869,-0.212410,1.434800,1.00056,4312.57,0.006381,0.008798,490180.427193,0,0,0.67905
11934,1,"alpha_dyn[2,1]",-6.449290,-7.700560,-5.221760,1.00153,2223.27,0.013427,0.004536,490180.427193,0,0,0.67905
13010,1,"alpha_dyn[4,3]",0.197134,-0.310808,0.711358,1.00049,4130.83,0.004040,0.008427,490180.427193,0,0,0.67905
13343,1,"alpha_dyn[3,2]",0.675293,0.254014,1.105220,1.00044,3172.98,0.003846,0.006473,490180.427193,0,0,0.67905
14252,1,"alpha_dyn[4,2]",0.913687,0.480880,1.369530,1.00038,2837.06,0.004280,0.005788,490180.427193,0,0,0.67905
19220,1,"alpha_dyn[4,1]",-3.475470,-4.526970,-2.426610,1.00020,2080.89,0.011618,0.004245,490180.427193,0,0,0.67905
36109,1,"alpha_dyn[2,2]",0.558092,0.077212,1.036980,1.00160,3004.30,0.004485,0.006129,490180.427193,0,0,0.67905
38331,1,"alpha_dyn[3,1]",-5.604200,-6.748570,-4.519980,1.00163,2127.40,0.012302,0.004340,490180.427193,0,0,0.67905
41500,1,"alpha_dyn[1,1]",-12.532500,-14.440500,-10.714800,1.00124,1621.73,0.023941,0.003308,490180.427193,0,0,0.67905
49070,1,"alpha_dyn[2,3]",0.951240,0.402763,1.505840,1.00041,3534.28,0.004738,0.007210,490180.427193,0,0,0.67905
51600,1,"alpha_dyn[1,2]",0.454730,-0.219913,1.142760,1.00024,3168.96,0.006143,0.006465,490180.427193,0,0,0.67905